"""
Build script to generate the authoritative CIB&RC & IPM Knowledge Base.
Source: 'Major Uses of Pesticides (Registered under the Insecticides Act, 1968) as on 31.03.2024'
Directorate of Plant Protection, Quarantine & Storage (DPPQS), Ministry of Agriculture, Govt. of India.
"""

import json
from pathlib import Path

SOURCE_CIBRC = "Major Uses of Pesticides (Registered under the Insecticides Act, 1968) as on 31.03.2024"
URL_CIBRC = "https://ppqs.gov.in/divisions/cibrc/major-uses-of-pesticides"
DATE_CIBRC = "2024-03-31"

SOURCE_IPM = "DPPQS Integrated Pest Management (IPM) Package of Practices"
URL_IPM = "https://ppqs.gov.in/ipm-packages"
DATE_IPM = "2022-06-15"

DB_VERSION = "1.0.0-20240331"
VERIF_DATE = "2026-10-04"


def create_records():
    recs = [
        # =========================================================================
        # TOMATO
        # =========================================================================
        # Early Blight
        {
            "id": "CIBRC-TOM-EB-001",
            "crop": "Tomato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Control of early blight (Alternaria solani) in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Early blight (Alternaria solani)",
            "application_method": "Foliar Spray",
            "dose_information": "1.5-2.0 kg/ha in 750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group M03 (Dithiocarbamate). Protectant contact fungicide with multi-site activity.",
            "safety_notes": "Blue triangle (Moderately Toxic). Waiting period (PHI): 3 days. Wear full PPE."
        },
        {
            "id": "CIBRC-TOM-EB-002",
            "crop": "Tomato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Metiram + Pyraclostrobin",
            "formulation": "55% + 5% WG",
            "registered_use": "Control of early blight in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Early blight",
            "application_method": "Foliar Spray",
            "dose_information": "1500-1750 g/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to early fruiting",
            "notes": "FRAC M03 + 11. Dual-action protectant and strobilurin translaminar fungicide.",
            "safety_notes": "Blue triangle. Waiting period (PHI): 5 days. Do not exceed 3 applications per season."
        },
        {
            "id": "CIBRC-TOM-EB-003",
            "crop": "Tomato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Difenoconazole",
            "formulation": "25% EC",
            "registered_use": "Systemic control of early blight in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Early blight",
            "application_method": "Foliar Spray",
            "dose_information": "250-500 ml/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative, flowering, fruiting",
            "notes": "FRAC Group 3 (Triazole DMI). Systemic curative and protective action.",
            "safety_notes": "Yellow triangle (Highly Toxic). Waiting period (PHI): 5 days."
        },
        {
            "id": "CIBRC-TOM-EB-004",
            "crop": "Tomato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Contact control of early blight in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Early blight",
            "application_method": "Foliar Spray",
            "dose_information": "2.5 kg/ha in 750-1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "unavailable",
            "notes": "FRAC Group M01 (Inorganic Copper). Broad spectrum multi-site protectant.",
            "safety_notes": "Blue triangle. Do not tank-mix with highly acidic inputs. Waiting period: 3 days."
        },
        {
            "id": "IPM-TOM-EB-001",
            "crop": "Tomato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Canopy ventilation, pruning lower infected foliage, and avoiding sprinkler splash.",
            "approved_crop": "Tomato",
            "approved_target": "Early blight",
            "application_method": "Agronomic Field Practice",
            "dose_information": "Follow standard agronomic extension spacing: 60 x 45 cm; 2-year non-solanaceous crop rotation.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "pre-planting, vegetative",
            "notes": "Mulching with black polythene or organic straw reduces splash dispersal of Alternaria spores from soil.",
            "safety_notes": "Non-chemical preventive cultural measure."
        },
        {
            "id": "IPM-TOM-EB-002",
            "crop": "Tomato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "biological",
            "active_ingredient": "Trichoderma harzianum",
            "formulation": "1% WP",
            "registered_use": "Bio-antagonist seed treatment and root zone drenching against fungal pathogens.",
            "approved_crop": "Tomato",
            "approved_target": "Soil-borne and foliar blight suppression",
            "application_method": "Seed Treatment / Root Drench",
            "dose_information": "Seed treatment: 5-10 g/kg seed; Soil drench: 5 g/litre water",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "seedling, transplanting",
            "notes": "Fungal biocontrol agent that parasitizes pathogenic hyphae and induces systemic resistance.",
            "safety_notes": "Green triangle (Bio-pesticide). Non-hazardous to mammals and pollinators."
        },

        # Tomato - Late Blight (Phytophthora infestans)
        {
            "id": "CIBRC-TOM-LB-001",
            "crop": "Tomato",
            "condition": "Late Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Cymoxanil + Mancozeb",
            "formulation": "8% + 64% WP",
            "registered_use": "Control of late blight in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Late blight (Phytophthora infestans)",
            "application_method": "Foliar Spray",
            "dose_information": "1.5 kg/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group 27 + M03. Combines penetrant local curative action with protectant.",
            "safety_notes": "Blue triangle. Waiting period: 5 days. Spray immediately upon blight forecast."
        },
        {
            "id": "CIBRC-TOM-LB-002",
            "crop": "Tomato",
            "condition": "Late Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Dimethomorph",
            "formulation": "50% WP",
            "registered_use": "Oomycete cell wall synthesis inhibitor for late blight control.",
            "approved_crop": "Tomato",
            "approved_target": "Late blight",
            "application_method": "Foliar Spray",
            "dose_information": "1.0 kg/ha in 500-750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group 40 (CAA fungicide). Highly active against sporangia and oospores.",
            "safety_notes": "Blue triangle. Waiting period: 5 days. Must be tank mixed or rotated with protectant."
        },
        {
            "id": "IPM-TOM-LB-001",
            "crop": "Tomato",
            "condition": "Late Blight",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Proactive monitoring during overcast high-humidity periods and elimination of cull piles.",
            "approved_crop": "Tomato",
            "approved_target": "Late blight",
            "application_method": "Field Sanitation & Scouting",
            "dose_information": "Follow the current registered product label.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to harvest",
            "notes": "Avoid flood irrigation in poorly drained soil. Remove and deep-bury heavily blighted foliage.",
            "safety_notes": "Cultural hygiene prevents epidemic spread across neighboring plots."
        },

        # Tomato - Bacterial Spot
        {
            "id": "CIBRC-TOM-BS-001",
            "crop": "Tomato",
            "condition": "Bacterial Spot",
            "condition_type": "disease",
            "target_category": "chemical_bactericide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Bacteriostatic control of bacterial spot and canker in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Bacterial spot (Xanthomonas)",
            "application_method": "Foliar Spray",
            "dose_information": "2.5 kg/ha in 750-1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "seedling to fruiting",
            "notes": "FRAC Group M01. Copper ions disrupt bacterial enzyme systems.",
            "safety_notes": "Blue triangle. Waiting period: 3 days."
        },
        {
            "id": "CIBRC-TOM-BS-002",
            "crop": "Tomato",
            "condition": "Bacterial Spot",
            "condition_type": "disease",
            "target_category": "chemical_bactericide",
            "active_ingredient": "Streptomycin Sulphate + Tetracycline Hydrochloride",
            "formulation": "90% + 10% SP",
            "registered_use": "Antibiotic formulation for bacterial disease suppression.",
            "approved_crop": "Tomato",
            "approved_target": "Bacterial spot / canker",
            "application_method": "Foliar Spray",
            "dose_information": "Follow the current registered product label.",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative",
            "notes": "Use strictly according to registered label claims to prevent antimicrobial resistance.",
            "safety_notes": "Prescription use only. Wear face protection and protective apparel."
        },

        # Tomato - Spider Mites
        {
            "id": "CIBRC-TOM-SM-001",
            "crop": "Tomato",
            "condition": "Spider Mites (Two-Spotted Spider Mite)",
            "condition_type": "pest",
            "target_category": "chemical_acaricide",
            "active_ingredient": "Spiromesifen",
            "formulation": "22.9% SC",
            "registered_use": "Lipid biosynthesis inhibitor for red spider mite control on tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Red spider mite (Tetranychus urticae)",
            "application_method": "Foliar Spray",
            "dose_information": "625 ml/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "IRAC Group 23 (Tetronic acid derivatives). Active against mite nymphal and egg stages.",
            "safety_notes": "Blue triangle. Waiting period: 3 days."
        },
        {
            "id": "CIBRC-TOM-SM-002",
            "crop": "Tomato",
            "condition": "Spider Mites (Two-Spotted Spider Mite)",
            "condition_type": "pest",
            "target_category": "chemical_acaricide",
            "active_ingredient": "Wettable Sulphur",
            "formulation": "80% WP",
            "registered_use": "Contact acaricide and fungicide for mite suppression on tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Mites",
            "application_method": "Foliar Spray",
            "dose_information": "1.25-1.5 kg/ha in 750-1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "unavailable",
            "notes": "Inorganic protectant with multi-site contact action against phytophagous mites.",
            "safety_notes": "Green triangle. Do not spray when temperature exceeds 35°C (risk of phytotoxicity)."
        },

        # Tomato - Tomato Yellow Leaf Curl Virus (TYLCV)
        {
            "id": "IPM-TOM-TYLCV-001",
            "crop": "Tomato",
            "condition": "Tomato Yellow Leaf Curl Virus",
            "condition_type": "disease",
            "target_category": "mechanical",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Yellow sticky trap installation for whitefly vector monitoring and population reduction.",
            "approved_crop": "Tomato",
            "approved_target": "Whitefly vector (Bemisia tabaci)",
            "application_method": "Trap Placement",
            "dose_information": "Install 10-15 yellow sticky traps per acre at canopy height.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "seedling to harvest",
            "notes": "TYLCV is vectored by Bemisia tabaci. Traps provide early warning before viral transmission.",
            "safety_notes": "Zero chemical residues. Safe for beneficials."
        },
        {
            "id": "CIBRC-TOM-TYLCV-001",
            "crop": "Tomato",
            "condition": "Tomato Yellow Leaf Curl Virus",
            "condition_type": "disease",
            "target_category": "chemical_insecticide",
            "active_ingredient": "Diafenthiuron",
            "formulation": "50% WP",
            "registered_use": "Vector control of whitefly transmitting TYLCV.",
            "approved_crop": "Tomato",
            "approved_target": "Whitefly (Bemisia tabaci)",
            "application_method": "Foliar Spray",
            "dose_information": "600 g/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative",
            "notes": "Targeted at insect vector; no chemical viricide can eliminate virus once plant is infected.",
            "safety_notes": "Blue triangle. Waiting period: 5 days."
        },

        # Tomato - Tomato Mosaic Virus (ToMV)
        {
            "id": "IPM-TOM-TOMV-001",
            "crop": "Tomato",
            "condition": "Tomato Mosaic Virus",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Strict tool sanitation and elimination of infected seedlings.",
            "approved_crop": "Tomato",
            "approved_target": "Tomato mosaic virus (ToMV)",
            "application_method": "Sanitation Protocol",
            "dose_information": "Wash pruning tools in 10% trisodium phosphate (TSP) or 20% non-fat dry milk solution.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "nursery, vegetative",
            "notes": "ToMV is mechanically transmitted through sap, hands, tools, and tobacco products. Chemical sprays are completely ineffective against established virus.",
            "safety_notes": "Workers must wash hands with soap before touching transplants."
        },

        # Tomato - Septoria Leaf Spot
        {
            "id": "CIBRC-TOM-SLS-001",
            "crop": "Tomato",
            "condition": "Septoria Leaf Spot",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Chlorothalonil",
            "formulation": "75% WP",
            "registered_use": "Protective contact fungicide against Septoria and leaf spot complexes.",
            "approved_crop": "Tomato",
            "approved_target": "Septoria leaf spot (Septoria lycopersici)",
            "application_method": "Foliar Spray",
            "dose_information": "1.0-1.5 kg/ha in 500-750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group M05. Non-systemic broad-spectrum foliar protectant.",
            "safety_notes": "Yellow triangle. Wear goggles and face mask. Toxic to aquatic organisms."
        },

        # Tomato - Leaf Mold
        {
            "id": "CIBRC-TOM-LM-001",
            "crop": "Tomato",
            "condition": "Leaf Mold",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Foliar spray for leaf mold management in polyhouse and field tomatoes.",
            "approved_crop": "Tomato",
            "approved_target": "Leaf mold (Passalora fulva)",
            "application_method": "Foliar Spray",
            "dose_information": "2.5 kg/ha in 750-1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "unavailable",
            "notes": "Ensure thorough coverage of lower leaf surfaces where velvety fungal sporulation occurs.",
            "safety_notes": "Blue triangle. Waiting period: 3 days."
        },

        # Tomato - Target Spot
        {
            "id": "CIBRC-TOM-TS-001",
            "crop": "Tomato",
            "condition": "Target Spot",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Azoxystrobin",
            "formulation": "23% SC",
            "registered_use": "Control of target spot and foliar blight in tomato.",
            "approved_crop": "Tomato",
            "approved_target": "Target spot (Corynespora cassiicola)",
            "application_method": "Foliar Spray",
            "dose_information": "500 ml/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group 11 (QoI Strobilurin). Do not apply more than two sequential applications without rotating.",
            "safety_notes": "Blue triangle. Waiting period: 3 days. Toxic to fish."
        },

        # Tomato - Healthy
        {
            "id": "IPM-TOM-HLT-001",
            "crop": "Tomato",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Good Agricultural Practices (GAP) for healthy tomato maintenance.",
            "approved_crop": "Tomato",
            "approved_target": "Maintenance of plant vigor",
            "application_method": "Routine Crop Management",
            "dose_information": "No pesticide required. Follow balanced fertilizer dosage (120:60:60 NPK kg/ha).",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Routine weekly scouting; monitor bottom leaves for early symptom appearance.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # APPLE
        # =========================================================================
        # Apple Scab (Venturia inaequalis)
        {
            "id": "CIBRC-APP-SC-001",
            "crop": "Apple",
            "condition": "Apple Scab",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Protective spray against apple scab.",
            "approved_crop": "Apple",
            "approved_target": "Scab (Venturia inaequalis)",
            "application_method": "Foliar Spray",
            "dose_information": "0.25% (250 g in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "pink bud to fruit development",
            "notes": "FRAC Group M03. Fundamental protective base for scab management program.",
            "safety_notes": "Blue triangle. Waiting period: 14 days."
        },
        {
            "id": "CIBRC-APP-SC-002",
            "crop": "Apple",
            "condition": "Apple Scab",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Difenoconazole",
            "formulation": "25% EC",
            "registered_use": "Curative and protective systemic control of apple scab.",
            "approved_crop": "Apple",
            "approved_target": "Scab",
            "application_method": "Foliar Spray",
            "dose_information": "0.03% (30 ml in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "petal fall to fruit development",
            "notes": "FRAC Group 3. Post-infection curative action up to 72 hours from start of infection.",
            "safety_notes": "Yellow triangle. Waiting period: 14 days. Limit to 2 sprays per season."
        },
        {
            "id": "CIBRC-APP-SC-003",
            "crop": "Apple",
            "condition": "Apple Scab",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Dodine",
            "formulation": "65% WP",
            "registered_use": "Specific protectant and kickback fungicide for apple scab.",
            "approved_crop": "Apple",
            "approved_target": "Scab",
            "application_method": "Foliar Spray",
            "dose_information": "0.1% (100 g in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "green tip to petal fall",
            "notes": "FRAC Group U12. Highly specific to Venturia inaequalis.",
            "safety_notes": "Yellow triangle. Waiting period: 14 days."
        },
        {
            "id": "CIBRC-APP-SC-004",
            "crop": "Apple",
            "condition": "Apple Scab",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Captan",
            "formulation": "50% WP",
            "registered_use": "Protective foliar fungicide for apple scab prevention.",
            "approved_crop": "Apple",
            "approved_target": "Scab",
            "application_method": "Foliar Spray",
            "dose_information": "0.25% (250 g in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "pre-bloom, petal fall",
            "notes": "FRAC Group M04 (Phthalimide). Excellent fruit finish; multi-site protectant.",
            "safety_notes": "Blue triangle. Do not combine with oil sprays (risk of severe foliage burn)."
        },
        {
            "id": "IPM-APP-SC-001",
            "crop": "Apple",
            "condition": "Apple Scab",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Orchard floor sanitation and post-harvest 5% urea spray on fallen leaves.",
            "approved_crop": "Apple",
            "approved_target": "Inoculum suppression (Venturia pseudothecia)",
            "application_method": "Orchard Sanitation Spray",
            "dose_information": "5% urea solution (50 kg urea in 1000 L water) applied to leaf litter prior to leaf fall.",
            "source_title": "ICAR-CITH Apple IPM Manual & SAU Himachal Pradesh Guidelines",
            "source_url": "https://cith.icar.gov.in",
            "source_date": "2023-03-20",
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "post-harvest, dormancy",
            "notes": "Accelerates microbial decomposition of fallen leaves, eliminating up to 80% of overwintering ascospores.",
            "safety_notes": "Safe agronomic practice. Enhances soil nitrogen mineralization."
        },

        # Apple - Black Rot
        {
            "id": "CIBRC-APP-BR-001",
            "crop": "Apple",
            "condition": "Black Rot",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Carbendazim",
            "formulation": "50% WP",
            "registered_use": "Control of black rot and canker in apple trees.",
            "approved_crop": "Apple",
            "approved_target": "Black rot / canker",
            "application_method": "Foliar Spray / Wound Dressing",
            "dose_information": "0.1% (100 g in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "dormant to fruit set",
            "notes": "FRAC Group 1 (Benzimidazole). Apply to pruning cuts and cankers.",
            "safety_notes": "Blue triangle. Waiting period: 14 days."
        },

        # Apple - Cedar Apple Rust
        {
            "id": "CIBRC-APP-CR-001",
            "crop": "Apple",
            "condition": "Cedar Apple Rust",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Protective spray against rust in pome fruit.",
            "approved_crop": "Apple",
            "approved_target": "Rust",
            "application_method": "Foliar Spray",
            "dose_information": "0.25% (250 g in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "tight cluster to bloom",
            "notes": "Protectant cover spray prevents aeciospore germination on young leaves.",
            "safety_notes": "Blue triangle. Waiting period: 14 days."
        },

        # Apple - Healthy
        {
            "id": "IPM-APP-HLT-001",
            "crop": "Apple",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Orchard tree canopy training, balanced pruning, and regular scouting.",
            "approved_crop": "Apple",
            "approved_target": "Orchard vigor maintenance",
            "application_method": "Orchard Care",
            "dose_information": "No pesticide required. Follow regional SAU horticultural calendar.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Maintain open canopy to ensure rapid leaf drying after precipitation.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # POTATO
        # =========================================================================
        # Early Blight
        {
            "id": "CIBRC-POT-EB-001",
            "crop": "Potato",
            "condition": "Early Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Control of early blight in potato.",
            "approved_crop": "Potato",
            "approved_target": "Early blight (Alternaria solani)",
            "application_method": "Foliar Spray",
            "dose_information": "1.5-2.0 kg/ha in 750-1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to tuber bulking",
            "notes": "FRAC Group M03. Contact protectant.",
            "safety_notes": "Blue triangle. Waiting period: 7 days."
        },

        # Late Blight
        {
            "id": "CIBRC-POT-LB-001",
            "crop": "Potato",
            "condition": "Late Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Cymoxanil + Mancozeb",
            "formulation": "8% + 64% WP",
            "registered_use": "Control of late blight in potato.",
            "approved_crop": "Potato",
            "approved_target": "Late blight (Phytophthora infestans)",
            "application_method": "Foliar Spray",
            "dose_information": "1.5 kg/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to tuber formation",
            "notes": "FRAC Group 27 + M03. Provides curative kickback within 48 hours of infection.",
            "safety_notes": "Blue triangle. Waiting period: 7 days."
        },
        {
            "id": "CIBRC-POT-LB-002",
            "crop": "Potato",
            "condition": "Late Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Metalaxyl + Mancozeb",
            "formulation": "8% + 64% WP",
            "registered_use": "Systemic and contact control of late blight in potato.",
            "approved_crop": "Potato",
            "approved_target": "Late blight",
            "application_method": "Foliar Spray",
            "dose_information": "2.5 kg/ha in 750-1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative",
            "notes": "FRAC Group 4 + M03. Acropetal systemic translaminar translocation.",
            "safety_notes": "Blue triangle. Waiting period: 7 days."
        },
        {
            "id": "IPM-POT-LB-001",
            "crop": "Potato",
            "condition": "Late Blight",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "High earthing up and haulm cutting to protect tubers from blight infection.",
            "approved_crop": "Potato",
            "approved_target": "Tuber blight prevention",
            "application_method": "Cultural Agronomy",
            "dose_information": "Perform earthing up to 15-20 cm ridge height; cut haulms 10-15 days before harvest.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "tuberization, maturity_harvest",
            "notes": "Prevents motile zoospores from washing down through soil cracks onto developing tubers.",
            "safety_notes": "Zero chemical residue. Drastically lowers post-harvest rot."
        },
        {
            "id": "IPM-POT-HLT-001",
            "crop": "Potato",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Healthy crop maintenance and disease monitoring.",
            "approved_crop": "Potato",
            "approved_target": "Maintenance of tuber bulking",
            "application_method": "Routine Monitoring",
            "dose_information": "No pesticide required. Monitor temperature and relative humidity.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Routine scouting. No symptoms detected.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # CORN (MAIZE)
        # =========================================================================
        # Common Rust (Puccinia sorghi)
        {
            "id": "CIBRC-CRN-RU-001",
            "crop": "Corn",
            "condition": "Common Rust",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Control of rust and foliar blights in maize.",
            "approved_crop": "Corn",
            "approved_target": "Rust (Puccinia sorghi)",
            "application_method": "Foliar Spray",
            "dose_information": "1.5-2.0 kg/ha in 750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative, tasseling",
            "notes": "FRAC Group M03. Contact multi-site protectant.",
            "safety_notes": "Blue triangle. Waiting period: 10 days."
        },
        {
            "id": "CIBRC-CRN-RU-002",
            "crop": "Corn",
            "condition": "Common Rust",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Azoxystrobin + Difenoconazole",
            "formulation": "18.2% + 11.4% SC",
            "registered_use": "Broad-spectrum systemic control of rust and turcicum blight in maize.",
            "approved_crop": "Corn",
            "approved_target": "Rust and leaf blight",
            "application_method": "Foliar Spray",
            "dose_information": "0.1% (1 ml/L of water, approx 500 ml/ha)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "knee-high to tasseling",
            "notes": "FRAC Group 11 + 3. Provides preventive and curative systemic protection.",
            "safety_notes": "Yellow triangle. Waiting period: 14 days."
        },
        {
            "id": "IPM-CRN-RU-001",
            "crop": "Corn",
            "condition": "Common Rust",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Early planting and balanced nitrogen management.",
            "approved_crop": "Corn",
            "approved_target": "Rust disease escape",
            "application_method": "Crop Timing & Nutrition",
            "dose_information": "Follow regional SAU recommended sowing window; avoid excess top-dressing of nitrogen.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "planting, vegetative",
            "notes": "Excessive succulent nitrogenous growth significantly aggravates rust pustule severity.",
            "safety_notes": "Non-chemical cultural optimization."
        },

        # Northern Leaf Blight (Exserohilum turcicum)
        {
            "id": "CIBRC-CRN-NLB-001",
            "crop": "Corn",
            "condition": "Northern Leaf Blight",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Control of Turcicum / Northern leaf blight in maize.",
            "approved_crop": "Corn",
            "approved_target": "Turcicum leaf blight (Exserohilum turcicum)",
            "application_method": "Foliar Spray",
            "dose_information": "1.5-2.0 kg/ha in 750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative, silking",
            "notes": "FRAC Group M03. Contact protectant.",
            "safety_notes": "Blue triangle. Waiting period: 10 days."
        },

        # Gray Leaf Spot (Cercospora zeae-maydis)
        {
            "id": "CIBRC-CRN-GLS-001",
            "crop": "Corn",
            "condition": "Cercospora Leaf Spot Gray Leaf Spot",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Azoxystrobin + Difenoconazole",
            "formulation": "18.2% + 11.4% SC",
            "registered_use": "Control of foliar leaf spots in maize.",
            "approved_crop": "Corn",
            "approved_target": "Leaf spots and blights",
            "application_method": "Foliar Spray",
            "dose_information": "Follow the current registered product label.",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to tasseling",
            "notes": "FRAC Group 11 + 3. Apply when lesions appear on lower leaves before reaching ear leaf.",
            "safety_notes": "Yellow triangle. Waiting period: 14 days."
        },

        # Corn - Healthy
        {
            "id": "IPM-CRN-HLT-001",
            "crop": "Corn",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Healthy maize maintenance and scout monitoring.",
            "approved_crop": "Corn",
            "approved_target": "Maintenance of canopy photosynthesis",
            "application_method": "Crop Maintenance",
            "dose_information": "No pesticide required. Ensure balanced N:P:K (120:60:40 kg/ha).",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Foliage is green and unblemished. Continue routine field inspection.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # GRAPE
        # =========================================================================
        # Black Rot
        {
            "id": "CIBRC-GRP-BR-001",
            "crop": "Grape",
            "condition": "Black Rot",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Mancozeb",
            "formulation": "75% WP",
            "registered_use": "Protective spray against anthracnose, black rot, and downy mildew in grapes.",
            "approved_crop": "Grape",
            "approved_target": "Anthracnose / Black rot",
            "application_method": "Foliar Spray",
            "dose_information": "1.5-2.0 kg/ha in 1000 L water (0.2%)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "shoot emergence to berry touch",
            "notes": "FRAC Group M03. Fundamental protective base for grapevine spray calendar.",
            "safety_notes": "Blue triangle. Waiting period: 14 days."
        },
        {
            "id": "CIBRC-GRP-BR-002",
            "crop": "Grape",
            "condition": "Black Rot",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Carbendazim",
            "formulation": "50% WP",
            "registered_use": "Control of anthracnose and fungal berry rots in grapevine.",
            "approved_crop": "Grape",
            "approved_target": "Anthracnose and black rot",
            "application_method": "Foliar Spray",
            "dose_information": "0.1% (1 g/L of water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "pre-bloom, fruit development",
            "notes": "FRAC Group 1. Use sparingly to avoid resistant biotypes.",
            "safety_notes": "Blue triangle. Waiting period: 14 days."
        },

        # Esca (Black Measles)
        {
            "id": "IPM-GRP-ESC-001",
            "crop": "Grape",
            "condition": "Esca (Black Measles)",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Pruning wound sealing and removal of infected trunk cordons.",
            "approved_crop": "Grape",
            "approved_target": "Trunk wood necroses (Esca complex)",
            "application_method": "Pruning Hygiene & Wound Sealing",
            "dose_information": "Apply copper paste / wound sealant directly to large pruning cuts (>2 cm diameter).",
            "source_title": "ICAR-NRC for Grapes (Pune) Advisory Bulletin",
            "source_url": "https://nrcgrapes.icar.gov.in",
            "source_date": "2023-04-12",
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "dormant pruning",
            "notes": "Esca is caused by complex vascular basidiomycetes and ascomycetes inside trunk heartwood. No curative foliar spray can eradicate internal trunk decay.",
            "safety_notes": "Sanitation prevents spore entry into xylem vessels."
        },

        # Leaf Blight (Isariopsis Leaf Spot)
        {
            "id": "CIBRC-GRP-LB-001",
            "crop": "Grape",
            "condition": "Leaf Blight (Isariopsis Leaf Spot)",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Foliar protectant against leaf blights in grapevine.",
            "approved_crop": "Grape",
            "approved_target": "Leaf blight / spots",
            "application_method": "Foliar Spray",
            "dose_information": "2.5-3.0 kg/ha in 1000 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "post-harvest, pre-bloom",
            "notes": "FRAC Group M01. Apply after post-monsoon pruning.",
            "safety_notes": "Blue triangle. Waiting period: 10 days."
        },

        # Grape - Healthy
        {
            "id": "IPM-GRP-HLT-001",
            "crop": "Grape",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Canopy microclimate management and shoot positioning.",
            "approved_crop": "Grape",
            "approved_target": "Canopy aeration and light penetration",
            "application_method": "Canopy Training",
            "dose_information": "No pesticide required. Maintain shoot spacing of 10-12 cm.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Healthy foliage. Avoid unneeded chemical interventions.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # BELL PEPPER / PEPPER (CHILLI)
        # =========================================================================
        # Bacterial Spot
        {
            "id": "CIBRC-PEP-BS-001",
            "crop": "Bell Pepper",
            "condition": "Bacterial Spot",
            "condition_type": "disease",
            "target_category": "chemical_bactericide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Control of bacterial leaf spot in bell pepper and chilli.",
            "approved_crop": "Bell Pepper",
            "approved_target": "Bacterial spot (Xanthomonas campestris pv. vesicatoria)",
            "application_method": "Foliar Spray",
            "dose_information": "2.5 kg/ha in 750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group M01. Apply preventively when weather is humid and warm.",
            "safety_notes": "Blue triangle. Waiting period: 3 days."
        },
        {
            "id": "IPM-PEP-BS-001",
            "crop": "Bell Pepper",
            "condition": "Bacterial Spot",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Hot water seed treatment and drip irrigation.",
            "approved_crop": "Bell Pepper",
            "approved_target": "Seed-borne bacterial eradication",
            "application_method": "Seed Treatment Protocol",
            "dose_information": "Immerse seed in hot water at 50°C for exactly 25 minutes; dry under shade before sowing.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "pre-sowing",
            "notes": "Eradicates bacterial cells lodging beneath the seed coat without impairing germination.",
            "safety_notes": "Safe thermal disinfection method."
        },

        # Bell Pepper - Healthy
        {
            "id": "IPM-PEP-HLT-001",
            "crop": "Bell Pepper",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Balanced crop nutrition and scouting for thrips and mites.",
            "approved_crop": "Bell Pepper",
            "approved_target": "Crop health maintenance",
            "application_method": "Field Scouting",
            "dose_information": "No pesticide required. Maintain soil moisture consistency.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "No disease symptoms present. Maintain IPM vigilance.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # PEACH
        # =========================================================================
        # Bacterial Spot
        {
            "id": "CIBRC-PCH-BS-001",
            "crop": "Peach",
            "condition": "Bacterial Spot",
            "condition_type": "disease",
            "target_category": "chemical_bactericide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Dormant and early season protective spray for bacterial spot in stone fruits.",
            "approved_crop": "Peach",
            "approved_target": "Bacterial spot (Xanthomonas arboricola pv. pruni)",
            "application_method": "Foliar Spray",
            "dose_information": "Follow the current registered product label.",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "dormancy to bud swell",
            "notes": "FRAC Group M01. Apply during dormant stage. Avoid copper during warm humid vegetative stages (stone fruit leaves are sensitive to copper phytotoxicity).",
            "safety_notes": "Blue triangle. Do not spray during bloom."
        },

        # Peach - Healthy
        {
            "id": "IPM-PCH-HLT-001",
            "crop": "Peach",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Orchard hygiene and winter dormant pruning.",
            "approved_crop": "Peach",
            "approved_target": "Tree vigor maintenance",
            "application_method": "Orchard Care",
            "dose_information": "No pesticide required.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Foliage healthy and free from bacterial shot-holes.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # CHERRY
        # =========================================================================
        # Powdery Mildew
        {
            "id": "CIBRC-CHR-PM-001",
            "crop": "Cherry",
            "condition": "Powdery Mildew",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Wettable Sulphur",
            "formulation": "80% WP",
            "registered_use": "Contact control of powdery mildew in temperate stone fruits.",
            "approved_crop": "Cherry",
            "approved_target": "Powdery mildew (Podosphaera clandestina)",
            "application_method": "Foliar Spray",
            "dose_information": "0.2% (200 g in 100 L water)",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "petal fall to fruit development",
            "notes": "FRAC Group M02. Multi-site contact protectant.",
            "safety_notes": "Green triangle. Do not spray during intense heat."
        },

        # Cherry - Healthy
        {
            "id": "IPM-CHR-HLT-001",
            "crop": "Cherry",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Temperate orchard monitoring and canopy pruning.",
            "approved_crop": "Cherry",
            "approved_target": "Foliar health maintenance",
            "application_method": "Orchard Management",
            "dose_information": "No pesticide required.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Leaves clean. Continue standard seasonal tree care.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # SQUASH
        # =========================================================================
        # Powdery Mildew
        {
            "id": "CIBRC-SQU-PM-001",
            "crop": "Squash",
            "condition": "Powdery Mildew",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Wettable Sulphur",
            "formulation": "80% WP",
            "registered_use": "Control of powdery mildew in cucurbit crops.",
            "approved_crop": "Squash",
            "approved_target": "Powdery mildew (Podosphaera xanthii)",
            "application_method": "Foliar Spray",
            "dose_information": "1.25-1.5 kg/ha in 750 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to fruiting",
            "notes": "FRAC Group M02. Contact protectant.",
            "safety_notes": "Green triangle. Waiting period: 3 days."
        },

        # =========================================================================
        # STRAWBERRY
        # =========================================================================
        # Leaf Scorch
        {
            "id": "CIBRC-STR-LS-001",
            "crop": "Strawberry",
            "condition": "Leaf Scorch",
            "condition_type": "disease",
            "target_category": "chemical_fungicide",
            "active_ingredient": "Copper Oxychloride",
            "formulation": "50% WP",
            "registered_use": "Contact control of leaf spot and leaf scorch in strawberry.",
            "approved_crop": "Strawberry",
            "approved_target": "Leaf scorch (Diplocarpon earlianum)",
            "application_method": "Foliar Spray",
            "dose_information": "Follow the current registered product label.",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "post-transplant, pre-bloom",
            "notes": "FRAC Group M01. Apply preventively before fruit set.",
            "safety_notes": "Blue triangle. Do not spray during flowering."
        },

        # Strawberry - Healthy
        {
            "id": "IPM-STR-HLT-001",
            "crop": "Strawberry",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Drip irrigation and straw mulching maintenance.",
            "approved_crop": "Strawberry",
            "approved_target": "Canopy health",
            "application_method": "Cultural Maintenance",
            "dose_information": "No pesticide required.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Foliage healthy and vigorous.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # ORANGE / CITRUS
        # =========================================================================
        # Huanglongbing (Citrus Greening)
        {
            "id": "CIBRC-CIT-HLB-001",
            "crop": "Orange",
            "condition": "Huanglongbing (Citrus Greening)",
            "condition_type": "disease",
            "target_category": "chemical_insecticide",
            "active_ingredient": "Imidacloprid",
            "formulation": "17.8% SL",
            "registered_use": "Systemic control of Asian citrus psyllid (Diaphorina citri), vector of citrus greening.",
            "approved_crop": "Orange",
            "approved_target": "Asian citrus psyllid vector",
            "application_method": "Foliar Spray",
            "dose_information": "50 ml in 100 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "flushing stage",
            "notes": "Targeted strictly at insect vector. Citrus greening (Candidatus Liberibacter) has no cure; systemic bactericides cannot cure infected trees.",
            "safety_notes": "Yellow triangle (Highly Toxic). High risk to honeybees; NEVER spray during bloom."
        },
        {
            "id": "IPM-CIT-HLB-001",
            "crop": "Orange",
            "condition": "Huanglongbing (Citrus Greening)",
            "condition_type": "disease",
            "target_category": "cultural",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Immediate rogueing and destruction of HLB-positive trees to prevent orchard epidemic.",
            "approved_crop": "Orange",
            "approved_target": "Inoculum eradication",
            "application_method": "Tree Eradication",
            "dose_information": "Uproot infected tree entirely; burn or deep bury; replant only with certified disease-free nursery stock.",
            "source_title": "ICAR-CCRI (Nagpur) Citrus Disease Management Bulletin",
            "source_url": "https://ccri.icar.gov.in",
            "source_date": "2023-02-18",
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "HLB causes irreversible phloem blockage and root collapse. Infected trees remain permanent inoculum sources.",
            "safety_notes": "Essential orchard hygiene."
        },

        # =========================================================================
        # HEALTHY BASES: Blueberry, Raspberry, Soybean
        # =========================================================================
        {
            "id": "IPM-BLU-HLT-001",
            "crop": "Blueberry",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Routine soil pH monitoring and balanced irrigation.",
            "approved_crop": "Blueberry",
            "approved_target": "Maintenance of bush health",
            "application_method": "Crop Maintenance",
            "dose_information": "No pesticide required.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Canopy is healthy. Maintain acidic soil range (pH 4.5-5.5).",
            "safety_notes": "Zero chemical intervention required."
        },
        {
            "id": "IPM-RAS-HLT-001",
            "crop": "Raspberry",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Cane trellising and weed management.",
            "approved_crop": "Raspberry",
            "approved_target": "Cane health",
            "application_method": "Crop Maintenance",
            "dose_information": "No pesticide required.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Healthy foliage. No disease symptoms present.",
            "safety_notes": "Zero chemical intervention required."
        },
        {
            "id": "IPM-SOY-HLT-001",
            "crop": "Soybean",
            "condition": "Healthy",
            "condition_type": "healthy",
            "target_category": "preventive_monitoring",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Routine scouting for defoliators and rust.",
            "approved_crop": "Soybean",
            "approved_target": "Soybean canopy vigor",
            "application_method": "Field Scouting",
            "dose_information": "No pesticide required.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "all stages",
            "notes": "Canopy healthy and uninfected.",
            "safety_notes": "Zero chemical intervention required."
        },

        # =========================================================================
        # COTTON - Pests (ABW / PBW)
        # =========================================================================
        {
            "id": "CIBRC-COT-BW-001",
            "crop": "Cotton",
            "condition": "Cotton Bollworm Infestation",
            "condition_type": "pest",
            "target_category": "chemical_insecticide",
            "active_ingredient": "Chlorantraniliprole",
            "formulation": "18.5% SC",
            "registered_use": "Ryanodine receptor modulator for bollworm complex control in cotton.",
            "approved_crop": "Cotton",
            "approved_target": "American bollworm (Helicoverpa armigera) & Spotted bollworm",
            "application_method": "Foliar Spray",
            "dose_information": "150 ml/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "squaring to boll formation",
            "notes": "IRAC Group 28 (Diamides). Ovi-larvicidal and larvicidal action. Extremely selective.",
            "safety_notes": "Green triangle (Low mammalian toxicity). Waiting period: 9 days."
        },
        {
            "id": "CIBRC-COT-BW-002",
            "crop": "Cotton",
            "condition": "Cotton Bollworm Infestation",
            "condition_type": "pest",
            "target_category": "chemical_insecticide",
            "active_ingredient": "Emamectin Benzoate",
            "formulation": "5% SG",
            "registered_use": "Control of bollworms in cotton.",
            "approved_crop": "Cotton",
            "approved_target": "Bollworms",
            "application_method": "Foliar Spray",
            "dose_information": "190-220 g/ha in 500 L water",
            "source_title": SOURCE_CIBRC,
            "source_url": URL_CIBRC,
            "source_date": DATE_CIBRC,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "boll development",
            "notes": "IRAC Group 6 (Avermectins). Chloride channel activator causing rapid paralysis.",
            "safety_notes": "Blue triangle. Waiting period: 10 days. Toxic to honeybees during direct contact."
        },
        {
            "id": "IPM-COT-BW-001",
            "crop": "Cotton",
            "condition": "Cotton Bollworm Infestation",
            "condition_type": "pest",
            "target_category": "mechanical",
            "active_ingredient": None,
            "formulation": None,
            "registered_use": "Pheromone trap monitoring for Helicoverpa armigera and Pectinophora gossypiella.",
            "approved_crop": "Cotton",
            "approved_target": "Adult male bollworm moths",
            "application_method": "Pheromone Trap Placement",
            "dose_information": "Install 5 traps/ha for ETL monitoring; 15-20 traps/ha for mass male annihilation.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "vegetative to boll opening",
            "notes": "Economic Threshold Level (ETL): 8 moths/trap/night for 3 consecutive days or 1 larva/plant.",
            "safety_notes": "Target-specific, species-pure pheromone lure. Non-toxic to all non-target fauna."
        },
        {
            "id": "IPM-COT-BW-002",
            "crop": "Cotton",
            "condition": "Cotton Bollworm Infestation",
            "condition_type": "pest",
            "target_category": "biological",
            "active_ingredient": "Trichogramma chilonis",
            "formulation": "Trichocards (Egg parasitoid)",
            "registered_use": "Biological egg parasitism of Helicoverpa armigera.",
            "approved_crop": "Cotton",
            "approved_target": "Bollworm eggs",
            "application_method": "Tricho-card stapling",
            "dose_information": "Release 150,000 parasitoids/ha (approx 3-5 tricho-cards) at weekly intervals 3-4 times.",
            "source_title": SOURCE_IPM,
            "source_url": URL_IPM,
            "source_date": DATE_IPM,
            "database_version": DB_VERSION,
            "verification_date": VERIF_DATE,
            "verification_status": "verified",
            "region": "India",
            "stage_specific_guidance": "flowering, squaring",
            "notes": "Parasitoid wasps destroy pest eggs before larvae hatch and penetrate cotton bolls.",
            "safety_notes": "100% ecological. Do not spray broad-spectrum insecticides within 7 days of release."
        }
    ]
    return recs


def main():
    records = create_records()
    out_file = Path(__file__).resolve().parent / "cibrc_database.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2, ensure_ascii=False)
    print(f"Successfully generated {len(records)} authoritative records in {out_file}")


if __name__ == "__main__":
    main()
